baseURL = 'https://kushshriv.github.io/portfolio/'
languageCode = 'en-us'
title = 'Kushaagra Shrivastava'
theme = "PaperMod"
enableInlineShortcodes = true

[params]
  hideFooter = true

  [params.profileMode]
    enabled = true
    title = "> Hey There! I am Kushaagra Shrivastava" # default will be site title
    subtitle = """
## 4th year CSE student @ PESU ECC 
---
#### Big Data & Data Analytics Enthusiast 
#### Cloud and Distributed Computing Enthusiast
#### Full-stack Developer.
---

I am still in the process of building this website, i will be filling up the information slowly.

Until then, feel free to look around and look at the main website in the link below!
"""
    imageUrl = "https://media.licdn.com/dms/image/D5603AQHK-rq0x2blAA/profile-displayphoto-shrink_800_800/0/1707554194158?e=1729123200&v=beta&t=AQhIHruhIKiaDOnizsxn0JAPNXK_cu8CRXBhwmbpn-Q" 
    imageTitle = "My image" # optional
    imageWidth = 200 # custom size
    imageHeight = 200 # custom size

    [[params.profileMode.buttons]]
      name = "View Resume"
      url = "https://drive.google.com/file/d/1VoTG6toOtnQc5mI-rK8y-AptKlo1wLiW/view?usp=sharing"

  [[params.socialIcons]]
    name = "Website"
    url = "http://kushshriv.github.io"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/kushaagra-shrivastava/"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/KushShriv"

  [[params.socialIcons]]
    name = "Email"
    url = "mailto:kushaagrashrivastava@gmail.com"



[menu]

  [[menu.main]]
    name = "Experience"
    url = "/portfolio/cs/experience/summary"
    weight = 1
  
  [[menu.main]]
    name = "Projects"
    url = "/portfolio/cs/project/highlight"
    weight = 2

  [[menu.main]]
    name = "Education"
    url = "/portfolio/cs/education/summary"
    weight = 3

  [[menu.main]]
    name = "Certifications"
    url = "/portfolio/cs/certifications/highlight"
    weight = 4

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/KushShriv/portfolio"
    weight = 0